services:
  react-frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: react-frontend
    ports:
      - "80:80"
    networks:
      - aqualife-network
      - ai_network
    depends_on:
      - fastapi-backend
      - ai-service
    environment:
      - COMPOSE_BAKE=true

  fastapi-backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    networks:
      - aqualife-network
    depends_on:
      - postgres
    env_file:  
      - .env
    environment:
      - COMPOSE_BAKE=true

  postgres:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - aqualife-network

  ai-service:
    build:
      context: .
      dockerfile: Dockerfile.aiService
    container_name: ai-service
    ports:
      - "8001:8001"
    networks:
      - ai_network
    env_file:
      - .env
    environment:
      - COMPOSE_BAKE=true
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-3.5-turbo}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}

networks:
  aqualife-network:
    driver: bridge
  ai_network:
    driver: bridge

volumes:
  postgres-data:
